os: linux
dist: xenial
language: java

env:
  - JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64

# Run before every job
before_install:
  - sudo apt-get update
  - sudo apt-get install -y openjdk-8-jdk
  - PATH=$(echo "$PATH" | sed -e 's/:\/usr\/local\/lib\/jvm\/openjdk11\/bin//')
  - java -version
  - uname -a
  - chmod +x pom.xml

# Only running report_coverage (after merge) to master branch
stages:
  - test

# List of jobs to run, tied to specific stages
jobs:
  include:
    - stage: test
      name: UnitTests
      script:
        - mvn test
