name: Testt
on: pull_request

permissions:
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    # The Secrect Actions GitHub example has three steps
    # Show how to print unmasked GitHub secrets to the console
    steps: 
      - name: Step 1 - Echo out a GitHub Actions Secret to the logs
        run: |
          echo "The GitHub Action Secret will be masked:  "
          echo ${{ secrets.TEST_TOKEN }}
          echo "Trick to echo GitHub Actions Secret:  "
          echo ${{secrets.TEST_TOKEN}} | sed 's/./& /g' 
      # Use a GitHub Actions secret variable in a bash shell
      - name: Step 2 - GitHub Action if statement (true)
        env: 
          WHO_TO_TRUST: ${{ secrets.TEST_TOKEN }}
        if:  env.WHO_TO_TRUST == 'test-token'
        run: echo "I know what the secret token is!"
